r4: r4.cpp
	g++ -O2 r4.cpp -o r4

r5: r5.cpp
	g++ -O2 r5.cpp -o r5
	
r6: r6.cpp
	g++ -O2 -fopenmp r6.cpp -o r6

r7: r7.cpp
	g++ -O2 -fopenmp r7.cpp -o r7

r8: r8.cpp
	g++ -O2 -fopenmp r8.cpp -o r8

r10: r10.cpp
	g++ -O2 -fopenmp r10.cpp -o r10

t1: t1.cpp
	g++ -O2 -fopenmp t1.cpp -o t1

t2: t2.cpp
	g++ -O2 -fopenmp t2.cpp -o t2

t3: t3.cpp
	g++ -O2 -fopenmp t3.cpp -o t3
